# netlify.toml

[build]
  # Thư mục chứa ứng dụng của bạn sau khi build. Đối với Vite, thường là 'dist'.
  # Vì đây là monorepo, đường dẫn sẽ là apps/react-quest-app/dist
  publish = "apps/react-quest-app/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200